# Generated by Django 4.1.1 on 2022-10-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.CharField(choices=[('Karachi', 'Karachi'), ('Hyderabad', 'Hyderabad'), ('Jamshoro', 'Jamshoro'), ('Ghotki', 'Ghotki'), ('Sukkur', 'Sukkur'), ('Lahore', 'Lahore'), ('Multan', 'Multan'), ('Rahim Yar Khan', 'Rahim Yar Khan'), ('Sadiqabad', 'Sadiqabad'), ('Peshawar', 'Peshawar'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Quetta', 'Quetta'), ('Khuzdar', 'Khuzdar'), ('Naushahro Feroze', 'Naushahro Feroze'), ('Shaheed Benazirabad', 'Shaheed Benazirabad'), ('Rawalpindi', 'Rawalpindi'), ('Faisalabad', 'Faisalabad'), ('Islamabad', 'Islamabad'), ('Thatta', 'Thatta')], max_length=100),
        ),
    ]
